name: What I saw
favicon: null
layout_spectrum: 0.2405584289226681
typography_spectrum: 0.3373885457403958
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.15532395686022937
  lightness: 0.498251027893275
  saturation: 0.4044019097927958
  rhythmicContrast: 0.2604301499668509
purpose: []
